# Form implementation generated from reading ui file 'dashboard/dashboard.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1422, 760)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(parent=Dialog)
        self.tabWidget.setObjectName("tabWidget")
        self.tabView = QtWidgets.QWidget()
        self.tabView.setObjectName("tabView")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tabView)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame = QtWidgets.QFrame(parent=self.tabView)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tableWidget = QtWidgets.QTableWidget(parent=self.frame)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.verticalLayout.addWidget(self.tableWidget)
        self.gridLayout_2.addWidget(self.frame, 1, 0, 1, 1)
        self.frame_2 = QtWidgets.QFrame(parent=self.tabView)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButtonFileOpen = QtWidgets.QPushButton(parent=self.frame_2)
        self.pushButtonFileOpen.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(
            QtGui.QPixmap(
                "dashboard/../icons/file_open_25dp_E3E3E3_FILL0_wght400_GRAD0_opsz24.png"
            ),
            QtGui.QIcon.Mode.Normal,
            QtGui.QIcon.State.Off,
        )
        self.pushButtonFileOpen.setIcon(icon)
        self.pushButtonFileOpen.setIconSize(QtCore.QSize(25, 25))
        self.pushButtonFileOpen.setObjectName("pushButtonFileOpen")
        self.horizontalLayout.addWidget(self.pushButtonFileOpen)
        self.pushButtonSettings = QtWidgets.QPushButton(parent=self.frame_2)
        self.pushButtonSettings.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(
            QtGui.QPixmap(
                "dashboard/../icons/settings_25dp_E3E3E3_FILL0_wght400_GRAD0_opsz24.png"
            ),
            QtGui.QIcon.Mode.Normal,
            QtGui.QIcon.State.Off,
        )
        self.pushButtonSettings.setIcon(icon1)
        self.pushButtonSettings.setIconSize(QtCore.QSize(25, 25))
        self.pushButtonSettings.setObjectName("pushButtonSettings")
        self.horizontalLayout.addWidget(self.pushButtonSettings)
        self.gridLayout_2.addWidget(
            self.frame_2, 0, 0, 1, 1, QtCore.Qt.AlignmentFlag.AlignLeft
        )
        self.tabWidget.addTab(self.tabView, "")
        self.tabPositioning = QtWidgets.QWidget()
        self.tabPositioning.setObjectName("tabPositioning")
        self.tabWidget.addTab(self.tabPositioning, "")
        self.tabAcquisition = QtWidgets.QWidget()
        self.tabAcquisition.setObjectName("tabAcquisition")
        self.tabWidget.addTab(self.tabAcquisition, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.frame_3 = QtWidgets.QFrame(parent=Dialog)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(parent=self.frame_3)
        self.label.setText("")
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.progressBar = QtWidgets.QProgressBar(parent=self.frame_3)
        self.progressBar.setMaximum(0)
        self.progressBar.setProperty("value", -1)
        self.progressBar.setObjectName("progressBar")
        self.horizontalLayout_2.addWidget(self.progressBar)
        self.gridLayout.addWidget(self.frame_3, 1, 0, 1, 1)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Whistle Of Wind"))
        self.tabWidget.setTabText(
            self.tabWidget.indexOf(self.tabView), _translate("Dialog", "View")
        )
        self.tabWidget.setTabText(
            self.tabWidget.indexOf(self.tabPositioning),
            _translate("Dialog", "Positioning"),
        )
        self.tabWidget.setTabText(
            self.tabWidget.indexOf(self.tabAcquisition),
            _translate("Dialog", "Acquisition"),
        )
